name: 构建 Rust 的 Linux 和 Windows 版本
on:
  push:
    branches:
      - '**'

env:
  ERJINZHI_DIR: erjinzhi

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码（完整历史）
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # - name: 安装 OpenSSL 开发库和 pkg-config
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libssl-dev pkg-config

      - name: 安装 Rust 稳定版
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: 添加 Windows 目标
        run: rustup target add x86_64-pc-windows-gnu

      - name: 安装 MinGW（用于交叉编译 Windows）
        run: sudo apt-get install -y mingw-w64

      - name: 创建 erjinzhi 文件夹
        run: mkdir -p "$ERJINZHI_DIR"

      - name: 构建 Linux x86_64 版本
        run: |
          cargo build --release
          cp target/release/aokege $ERJINZHI_DIR/aokege-linux-x86_64

      - name: 构建 Windows x86_64 版本
        run: |
          cargo build --release --target x86_64-pc-windows-gnu
          cp target/x86_64-pc-windows-gnu/release/aokege.exe $ERJINZHI_DIR/aokege-windows-x86_64.exe

      - name: 提交二进制文件到仓库
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          git config --global --unset credential.helper
          git config user.name "奥科戈 CI BOT"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $ERJINZHI_DIR/
          git commit -m "添加 Linux 和 Windows 编译好的二进制文件到 /${ERJINZHI_DIR}" || echo "没有需要提交的更改"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:master
